<MainLayout>

    BoxLayout:
        cols:2
        size: root.width, root.height

        BoxLayout:

            size_hint: (.05,1)

            Button:
                text: "Grid1"
                size_hint: (.1,1)

        BoxLayout:

            orientation:"horizontal"
            size_hint: (.4,1)
            padding: 8


            Button:
                text: "Grid2"
                size_hint: (.5,1)

            Button:
                text: "Grid3"
                size_hint: (.85,1)


        BoxLayout:
            orientation: "vertical"

            BoxLayout:
                orientation: "horizontal"

                padding: 8
                spacing: 10

                Button:
                    text: "Box1"
                    size_hint: (.5,1)

                Button:
                    text: "Box2"
                    size_hint: (.5,1)

            BoxLayout:
                orientation: "horizontal"
                cols:2
                size_hint: (1,0.5)
                padding: 10
                spacing: 10

                FloatLayout:
                    Button:
                        text: "Box31"
                        size_hint:(0.85,1)
                        pos_hint: {"x":0.001, "y":0.02}

                    RoundButton:
                        pos_hint: {"x":0.88, "y":0.7}
                        text: "Box321"
                        outline_color: (0,0,0)
                        outline_width: 1
                        size_hint: (.1,0.2)

                    RoundButton:
                        pos_hint: {"x":0.88, "y":0.4}
                        text: "Box322"
                        outline_color: (0,0,0)
                        outline_width: 1
                        size_hint: (.1,0.2)

                    RoundButton:
                        pos_hint: {"x":0.88, "y":0.1}
                        text: "Box323"
                        outline_color: (0,0,0)
                        outline_width: 1
                        size_hint: (.1,0.2)

            BoxLayout:
                orientation: "horizontal"
                padding: 10
                spacing: 10

                Button:
                    text: "Box4"
                    size_hint: (.8,1)

                Button:
                    text: "Box5"
                    outline_color: (0,0,0)
                    outline_width: 1
                    size_hint: (.2,1)
                    background_normal:''
                    background_color:(0,1,1,0.5)

<RoundButton@Button>

    background_normal: ''
    background_color:(0,0,0,0)
    canvas.before:
        Color:
            rgba:(0,1,1,0.5)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius:[10]
