<MainLayout>
    id:widget

    BoxLayout:
    #Mainbox
        cols:2
        size: root.width, root.height

        BoxLayout:
            #Grid1
            size_hint: (.05,1)

            Button:
                text: "Grid1"
                size_hint: (.1,1)

        BoxLayout:
            # Grid2
            orientation:"horizontal"
            size_hint: (.4,1)
            padding: 8

            BoxLayout:

                orientation:"vertical"
                size_hint: (0.4,1)

                FileChooserIconView:
                    id:filechooser
                    on_selection: widget.selected(filechooser.selection)


            Button:
                text: "Grid3"
                size_hint: (.85,1)


        BoxLayout:
            #Functionbox
            orientation: "vertical"

            BoxLayout:
                orientation: "horizontal"

                padding: 8
                spacing: 10

                FullImage:
                    #Box1
                    id: image1

                    source: ""
                    nocache: True

                    size_hint: (.5,1)

                FullImage:
                    #Box2
                    id: image2

                    source: ""
                    nocache: True

                    size_hint: (.5,1)

            BoxLayout:
                orientation: "horizontal"
                cols:2
                size_hint: (1,0.5)
                padding: 10
                spacing: 10

                FloatLayout:
                    Button:
                        text: "Box31"
                        size_hint:(0.85,1)
                        pos_hint: {"x":0.001, "y":0.02}

                    RoundButton:
                        #Box321
                        pos_hint: {"x":0.88, "y":0.7}
                        text: "Save"
                        outline_color: (0,0,0)
                        outline_width: 1
                        size_hint: (.1,0.2)
                        on_press: root.download()

                    RoundButton:
                        #Box322
                        pos_hint: {"x":0.88, "y":0.4}
                        text: "Preview"
                        outline_color: (0,0,0)
                        outline_width: 1
                        size_hint: (.1,0.2)
                        on_press: root.preview()

                    RoundButton:
                        #Box323
                        pos_hint: {"x":0.88, "y":0.1}
                        text: "Apply"
                        outline_color: (0,0,0)
                        outline_width: 1
                        size_hint: (.1,0.2)
                        on_press: root.apply()

            BoxLayout:
                orientation: "horizontal"
                padding: 10
                spacing: 10

                FloatLayout:
                    orientation: "vertical"
                    size_hint:(0.15,1)

                    Label:
                        pos_hint: {"x":0.3, "y":0.80}
                        size_hint: (.1,0.2)
                        text: "Saturation"

                    Label:
                        pos_hint: {"x":0.3, "y":0.62}
                        size_hint: (.1,0.2)
                        text: "Brightness"

                    Label:
                        pos_hint: {"x":0.23, "y":0.44}
                        size_hint: (.1,0.2)
                        text: "Contrast"

                    Label:
                        pos_hint: {"x":0.35, "y":0.26}
                        size_hint: (.1,0.2)
                        text: "Smoothness"

                    Label:
                        pos_hint: {"x":0.25, "y":0.08}
                        size_hint: (.1,0.2)
                        text: "Sharpness"


                FloatLayout:

                    Slider:
                        id:saturation_slider
                        pos_hint: {"x":0, "y":0.62}
                        min:1
                        max:100
                        step:5
                        size_hint: (.4,0.2)
                        on_value: root.slide_it(*args)

                    Slider:
                        id:bright_slider
                        pos_hint: {"x":0, "y":0.44}
                        min:1
                        max:100
                        step:5
                        size_hint: (.4,0.2)
                        on_value: root.slide_it(*args)

                    Slider:
                        id:contrast_slider
                        pos_hint: {"x":0, "y":0.26}
                        min:1
                        max:100
                        step:5
                        size_hint: (.4,0.2)
                        on_value: root.slide_it(*args)

                    Slider:
                        id:smooth_slider
                        pos_hint: {"x":0, "y":0.8}
                        min:1
                        max:100
                        step:5
                        size_hint: (.4,0.2)
                        on_value: root.slide_it(*args)

                    Slider:
                        id:sharp_slider
                        pos_hint: {"x":0, "y":0.08}
                        min:1
                        max:100
                        step:5
                        size_hint: (.4,0.2)
                        on_value: root.slide_it(*args)



                Button:
                    text: "Box5"
                    outline_color: (0,0,0)
                    outline_width: 1
                    size_hint: (.2,1)
                    background_normal:''
                    background_color:(0,1,1,0.5)




<RoundButton@Button>

    background_normal: ''
    background_color:(0,0,0,0)
    canvas.before:
        Color:
            rgba:(0,1,1,0.5)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius:[10]
